"""empty message

Revision ID: 5c4e5fa2c5ac
Revises: ed3530487ea0
Create Date: 2024-09-19 01:58:16.238112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4e5fa2c5ac'
down_revision = 'ed3530487ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('planet_origin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=42),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.String(length=42),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('planet_origin_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
