"""empty message

Revision ID: 8b9a0d27968e
Revises: b4559d816c8e
Create Date: 2024-09-18 15:44:08.219712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9a0d27968e'
down_revision = 'b4559d816c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=42), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('diameter', sa.Float(), nullable=False),
    sa.Column('orbital_period', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('weater', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=42), nullable=False),
    sa.Column('crew', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=15), nullable=False),
    sa.Column('cargo_capacity', sa.Float(), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('planet_origin_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'])
        batch_op.create_foreign_key(None, 'planet', ['planet_origin_id'], ['id'])
        batch_op.drop_column('ki')
        batch_op.drop_column('race')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'])
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicle_id')
        batch_op.drop_column('planet_id')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race', sa.VARCHAR(length=42), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ki', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicle_id')
        batch_op.drop_column('planet_origin_id')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')

    op.drop_table('vehicle')
    op.drop_table('planet')
    # ### end Alembic commands ###
